steps:
  # Paso 1: Instala las dependencias y compila la aplicaci칩n para producci칩n
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci
        npm run build  # Compila el proyecto con el archivo .env.production

  # Paso 2: Construye la imagen Docker para servir los archivos est치ticos
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/arriendos-vacacionales-internal-frontend', '.']

  # Paso 3: Publica la imagen en Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/arriendos-vacacionales-internal-frontend']

  # Paso 4: Despliega la imagen en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'arriendos-vacacionales-internal-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/arriendos-vacacionales-internal-frontend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1' # Cambia la regi칩n si es necesario
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/arriendos-vacacionales-internal-frontend'
